//! Privacy-safe, bounded solver-run telemetry.
//!
//! This is intentionally separate from the per-school/account execution and
//! billing ledgers in `serverless.rs`.  It must never store a timetable,
//! request body, school/account/user identifier, raw error, or browser event
//! identifier.  The only durable event key is a one-way digest used for
//! idempotency.  Super Admin receives aggregates only.

use crate::db::Db;
use rusqlite::{params, OptionalExtension};
use serde_json::{json, Map, Value};
use sha2::{Digest, Sha256};
use std::collections::{BTreeMap, HashMap};
use std::sync::{Arc, Mutex, OnceLock};
use std::time::{Instant, SystemTime, UNIX_EPOCH};

pub const FET_EVENT_MAX_BODY_BYTES: usize = 8 * 1024;
const RETENTION_MS: u64 = 90 * 24 * 60 * 60 * 1_000;
const MAX_EVENT_ROWS: i64 = 100_000;
const RATE_WINDOW_MS: u64 = 60 * 60 * 1_000;
const FET_EVENTS_PER_WINDOW: u32 = 120;
const MAX_RUNTIME_MS: u64 = 24 * 60 * 60 * 1_000;
const MAX_METRIC_VALUE: i64 = 1_000_000_000;
const MAX_COST_USD: f64 = 1_000.0;

#[derive(Clone, Debug)]
pub struct ServerRunMetadata {
    pub executor: String,
    pub focus: String,
    pub gap_target: String,
    pub budget_kind: String,
    pub budget_seconds: u64,
    /// Numeric UI baseline/target only.  These are aggregate-safe quality
    /// counters, never timetable cells or an identifier.
    pub metric_baseline: Option<i64>,
    pub target_metric: Option<i64>,
    pub profile: Option<String>,
    pub cloud_digest: Option<String>,
}

impl ServerRunMetadata {
    /// Copies a compact, canonical allowlist from solver settings.  The full
    /// request is deliberately not retained by this type or written to SQLite.
    pub fn from_request(
        executor: &str,
        request: Option<&Value>,
        profile: Option<&str>,
        cloud_digest: Option<&str>,
    ) -> Self {
        let executor = normalize_executor(executor).unwrap_or("vps").to_string();
        let settings = request
            .and_then(|request| request.get("settings"))
            .and_then(Value::as_object);
        let (focus, gap_target) = canonical_focus(settings);
        let (budget_kind, budget_seconds) = canonical_budget(&executor, settings);
        let metric_key = canonical_metric_key(&focus, &gap_target);
        let metric_baseline = metric_key
            .as_deref()
            .and_then(|key| metric_baseline_setting(settings, key));
        let target_metric = metric_key
            .as_deref()
            .and_then(|key| metric_target_setting(settings, key));
        Self {
            executor,
            focus,
            gap_target,
            budget_kind,
            budget_seconds,
            metric_baseline,
            target_metric,
            profile: profile.and_then(sanitize_profile),
            cloud_digest: cloud_digest.and_then(sanitize_digest),
        }
    }
}

/// An in-memory server-side attempt.  The opaque durable key is generated by
/// the caller-independent constructor, never from a job, account, school or
/// schedule ID.  A Drop fallback makes an unexpected coordinator exit visible
/// as a sanitised failed event instead of leaving a permanent `running` row.
pub struct ServerRun {
    db: Arc<Db>,
    key: String,
    metadata: ServerRunMetadata,
    started_at_ms: u64,
    started: Instant,
    finished: bool,
}

impl ServerRun {
    pub fn start(db: Arc<Db>, metadata: ServerRunMetadata) -> Self {
        let started_at_ms = now_millis();
        let key = generated_event_key();
        let run = Self {
            db,
            key,
            metadata,
            started_at_ms,
            started: Instant::now(),
            finished: false,
        };
        let _ = insert_server_start(&run.db, &run.key, &run.metadata, run.started_at_ms);
        run
    }

    pub fn finish(
        &mut self,
        outcome: &str,
        payload: Option<&Value>,
        fallback: Option<&str>,
        cost_estimate_usd: Option<f64>,
    ) {
        if self.finished {
            return;
        }
        let runtime_ms = self.started.elapsed().as_millis().min(u64::MAX as u128) as u64;
        let facts = TerminalFacts::from_payload(
            payload,
            &self.metadata.focus,
            &self.metadata.gap_target,
            self.metadata.metric_baseline,
            self.metadata.target_metric,
            outcome,
            fallback,
        );
        let _ = finish_server_run(&self.db, &self.key, runtime_ms, facts, cost_estimate_usd);
        self.finished = true;
    }
}

impl Drop for ServerRun {
    fn drop(&mut self) {
        if !self.finished {
            self.finish("failed", None, Some("coordinator_exit"), None);
        }
    }
}

#[derive(Clone, Debug)]
struct BrowserFetEvent {
    key: String,
    focus: String,
    gap_target: String,
    budget_kind: String,
    budget_seconds: u64,
    runtime_ms: u64,
    outcome: String,
    result_kind: String,
    fallback: String,
    hard_valid: Option<bool>,
    applied: Option<bool>,
    target_reached: Option<bool>,
    floor_reached: Option<bool>,
    metric_key: Option<String>,
    metric_before: Option<i64>,
    metric_after: Option<i64>,
    metric_delta: Option<i64>,
    target_metric: Option<i64>,
    floor_metric: Option<i64>,
}

#[derive(Clone, Debug)]
struct TerminalFacts {
    outcome: String,
    result_kind: String,
    fallback: String,
    hard_valid: Option<bool>,
    applied: Option<bool>,
    target_reached: Option<bool>,
    floor_reached: Option<bool>,
    metric_key: Option<String>,
    metric_before: Option<i64>,
    metric_after: Option<i64>,
    metric_delta: Option<i64>,
    target_metric: Option<i64>,
    floor_metric: Option<i64>,
    cloud_revision: Option<String>,
    cloud_digest: Option<String>,
}

impl TerminalFacts {
    fn from_payload(
        payload: Option<&Value>,
        focus: &str,
        gap_target: &str,
        metric_baseline_hint: Option<i64>,
        target_metric_hint: Option<i64>,
        requested_outcome: &str,
        fallback: Option<&str>,
    ) -> Self {
        let outcome = normalize_outcome(requested_outcome);
        let result_kind = payload
            .and_then(|value| {
                value
                    .get("kind")
                    .or_else(|| value.get("resultKind"))
                    .or_else(|| value.get("failureKind"))
                    .and_then(Value::as_str)
            })
            .map(normalize_result_kind)
            .unwrap_or_else(|| outcome.clone());
        let metrics = payload.and_then(|value| value.get("metrics"));
        let metric_key = canonical_metric_key(focus, gap_target);
        let metric_after = metric_key
            .as_deref()
            .and_then(|key| metric_value(metrics, key));
        let metric_before = metric_key
            .as_deref()
            .and_then(|key| metric_baseline_value(payload, key))
            .or(metric_baseline_hint);
        let metric_delta = match (metric_before, metric_after) {
            (Some(before), Some(after)) => before.checked_sub(after),
            _ => None,
        };
        let target_metric = payload
            .and_then(|value| value.get("targetMetric"))
            .and_then(nonnegative_metric)
            .or_else(|| {
                payload
                    .and_then(|value| value.get("metrics"))
                    .and_then(|metrics| metrics.get("target_metric"))
                    .and_then(nonnegative_metric)
            })
            .or(target_metric_hint)
            .or_else(|| (focus != "sessions" && metric_key.is_some()).then_some(0));
        let floor_metric = payload
            .and_then(|value| value.get("floorMetric"))
            .and_then(nonnegative_metric)
            .or_else(|| {
                metric_key
                    .as_deref()
                    .and_then(|key| metric_floor_value(metrics, key))
            });
        let target_reached = bool_from_paths(
            payload,
            &[
                &["targetReached"],
                &["target_reached"],
                &["metrics", "target_reached"],
            ],
        )
        .or_else(|| {
            metric_after.and_then(|metric| {
                target_metric
                    .map(|target| metric <= target)
                    .or_else(|| (focus != "sessions").then_some(metric == 0))
            })
        });
        let floor_reached = bool_from_paths(
            payload,
            &[
                &["floorReached"],
                &["floor_reached"],
                &["metrics", "floor_reached"],
            ],
        )
        .or_else(|| match (metric_after, floor_metric) {
            (Some(metric), Some(floor)) => Some(metric <= floor),
            _ => None,
        });
        let hard_valid = bool_from_paths(
            payload,
            &[
                &["hardValid"],
                &["hard_valid"],
                &["validation", "hardValid"],
                &["validation", "hard_valid"],
            ],
        )
        .or_else(|| inferred_hard_valid(payload));
        let applied = bool_from_paths(
            payload,
            &[["applied"].as_slice(), ["candidateApplied"].as_slice()],
        );
        let cloud_revision = payload
            .and_then(|value| runtime_string(value, "cloud_revision"))
            .or_else(|| payload.and_then(|value| runtime_string(value, "cloud_run_revision")))
            .and_then(sanitize_revision);
        let cloud_digest = payload
            .and_then(|value| runtime_string(value, "cloud_solver_digest"))
            .or_else(|| payload.and_then(|value| runtime_string(value, "cloud_digest")))
            .and_then(sanitize_digest);

        Self {
            outcome,
            result_kind,
            fallback: normalize_fallback(fallback.unwrap_or("none")),
            hard_valid,
            applied,
            target_reached,
            floor_reached,
            metric_key,
            metric_before,
            metric_after,
            metric_delta,
            target_metric,
            floor_metric,
            cloud_revision,
            cloud_digest,
        }
    }
}

/// Strictly validates and stores a browser FET terminal event.  `actor_key` and
/// `client_ip` are used only in a process-local rate bucket; neither is placed
/// in SQLite or returned in a response.
pub fn record_browser_fet_event(
    db: &Db,
    actor_key: &str,
    client_ip: &str,
    body: &[u8],
) -> Result<bool, TelemetryError> {
    if body.len() > FET_EVENT_MAX_BODY_BYTES {
        return Err(TelemetryError::TooLarge);
    }
    let value = serde_json::from_slice::<Value>(body).map_err(|_| TelemetryError::Invalid)?;
    let event = BrowserFetEvent::from_value(&value)?;

    if event_exists(db, &event.key).map_err(|_| TelemetryError::Storage)? {
        return Ok(false);
    }
    if !fet_rate_limiter().allow(actor_key, client_ip, now_millis()) {
        return Err(TelemetryError::RateLimited);
    }

    let inserted = insert_browser_event(db, &event).map_err(|_| TelemetryError::Storage)?;
    Ok(inserted)
}

impl BrowserFetEvent {
    fn from_value(value: &Value) -> Result<Self, TelemetryError> {
        let object = value.as_object().ok_or(TelemetryError::Invalid)?;
        const ALLOWED: &[&str] = &[
            "eventId",
            "executor",
            "focus",
            "gapTarget",
            "budgetKind",
            "budgetSeconds",
            "runtimeMs",
            "outcome",
            "resultKind",
            "fallback",
            "hardValid",
            "applied",
            "targetReached",
            "floorReached",
            "metricKey",
            "metricBefore",
            "metricAfter",
            "metricDelta",
            "targetMetric",
            "floorMetric",
        ];
        if object.keys().any(|key| !ALLOWED.contains(&key.as_str())) {
            return Err(TelemetryError::Invalid);
        }
        let event_id = string_field(object, "eventId")?;
        if !valid_opaque_event_id(event_id) {
            return Err(TelemetryError::Invalid);
        }
        if string_field(object, "executor")? != "fet_web_worker" {
            return Err(TelemetryError::Invalid);
        }
        let (focus, gap_target) = canonical_browser_focus(
            string_field(object, "focus")?,
            optional_string_field(object, "gapTarget")?,
        )
        .ok_or(TelemetryError::Invalid)?;
        let budget_kind = string_field(object, "budgetKind")?;
        if budget_kind != "local" {
            return Err(TelemetryError::Invalid);
        }
        let budget_seconds = unsigned_field(object, "budgetSeconds")?;
        if !(1..=300).contains(&budget_seconds) {
            return Err(TelemetryError::Invalid);
        }
        let runtime_ms = unsigned_field(object, "runtimeMs")?;
        if runtime_ms > MAX_RUNTIME_MS {
            return Err(TelemetryError::Invalid);
        }
        let outcome =
            browser_outcome(string_field(object, "outcome")?).ok_or(TelemetryError::Invalid)?;
        let result_kind = browser_result_kind(string_field(object, "resultKind")?)
            .ok_or(TelemetryError::Invalid)?;
        let fallback = optional_string_field(object, "fallback")?
            .map(browser_fallback)
            .transpose()
            .map_err(|_| TelemetryError::Invalid)?
            .unwrap_or_else(|| "none".to_string());
        let hard_valid = optional_bool_field(object, "hardValid")?;
        let applied = optional_bool_field(object, "applied")?;
        let target_reached = optional_bool_field(object, "targetReached")?;
        let floor_reached = optional_bool_field(object, "floorReached")?;
        let metric_key = optional_string_field(object, "metricKey")?.map(ToOwned::to_owned);
        let metric_before = optional_nonnegative_metric(object, "metricBefore")?;
        let metric_after = optional_nonnegative_metric(object, "metricAfter")?;
        let metric_delta = optional_signed_metric(object, "metricDelta")?;
        let target_metric = optional_nonnegative_metric(object, "targetMetric")?;
        let floor_metric = optional_nonnegative_metric(object, "floorMetric")?;

        if metric_key.is_some()
            || metric_before.is_some()
            || metric_after.is_some()
            || metric_delta.is_some()
            || target_metric.is_some()
            || floor_metric.is_some()
        {
            let expected =
                canonical_metric_key(&focus, &gap_target).ok_or(TelemetryError::Invalid)?;
            if metric_key.as_deref() != Some(expected.as_str()) {
                return Err(TelemetryError::Invalid);
            }
        }
        if let (Some(before), Some(after), Some(delta)) =
            (metric_before, metric_after, metric_delta)
        {
            if before.checked_sub(after) != Some(delta) {
                return Err(TelemetryError::Invalid);
            }
        }
        if floor_metric
            .zip(metric_after)
            .is_some_and(|(floor, after)| floor > after)
        {
            return Err(TelemetryError::Invalid);
        }

        Ok(Self {
            key: digest_event_id("browser-fet", event_id),
            focus,
            gap_target,
            budget_kind: "local".to_string(),
            budget_seconds,
            runtime_ms,
            outcome,
            result_kind,
            fallback,
            hard_valid,
            applied,
            target_reached,
            floor_reached,
            metric_key,
            metric_before,
            metric_after,
            metric_delta,
            target_metric,
            floor_metric,
        })
    }
}

#[derive(Debug)]
pub enum TelemetryError {
    Invalid,
    TooLarge,
    RateLimited,
    Storage,
}

impl TelemetryError {
    pub fn kind(&self) -> &'static str {
        match self {
            Self::Invalid => "solver_telemetry_invalid",
            Self::TooLarge => "solver_telemetry_too_large",
            Self::RateLimited => "solver_telemetry_rate_limited",
            Self::Storage => "solver_telemetry_unavailable",
        }
    }
}

/// Aggregate-only Super Admin response.  `window` is intentionally a closed
/// set to keep scans bounded and make the UI label unambiguous.
pub fn aggregate_for_window(db: &Db, window: &str) -> Result<Value, TelemetryError> {
    let window_ms = match window {
        "24h" => 24 * 60 * 60 * 1_000,
        "7d" => 7 * 24 * 60 * 60 * 1_000,
        "30d" => 30 * 24 * 60 * 60 * 1_000,
        _ => return Err(TelemetryError::Invalid),
    };
    ensure_storage(db).map_err(|_| TelemetryError::Storage)?;
    let generated_at_ms = now_millis();
    let since_ms = generated_at_ms.saturating_sub(window_ms);
    let aggregate = db
        .with_immediate_transaction(|tx| {
            let mut statement = tx.prepare(
                "SELECT source, executor, focus, gap_target, budget_kind, budget_seconds, \
                        runtime_ms, outcome, result_kind, fallback_kind, hard_valid, applied, \
                        target_reached, floor_reached, metric_key, metric_before, metric_after, \
                        metric_delta, target_metric, floor_metric, profile, cloud_revision, \
                        cloud_digest, cost_estimate_usd \
                 FROM solver_telemetry_events \
                 WHERE created_at_ms >= ?1 \
                 ORDER BY created_at_ms ASC, event_key ASC \
                 LIMIT ?2",
            )?;
            let rows =
                statement.query_map(params![sqlite_i64(since_ms), MAX_EVENT_ROWS], |row| {
                    Ok(TelemetryRow {
                        source: row.get(0)?,
                        executor: row.get(1)?,
                        focus: row.get(2)?,
                        gap_target: row.get(3)?,
                        budget_kind: row.get(4)?,
                        budget_seconds: nonnegative_u64(row.get::<_, i64>(5)?),
                        runtime_ms: nullable_nonnegative_u64(row.get::<_, Option<i64>>(6)?),
                        outcome: row.get(7)?,
                        result_kind: row.get(8)?,
                        fallback: row.get(9)?,
                        hard_valid: nullable_bool(row.get::<_, Option<i64>>(10)?),
                        applied: nullable_bool(row.get::<_, Option<i64>>(11)?),
                        target_reached: nullable_bool(row.get::<_, Option<i64>>(12)?),
                        floor_reached: nullable_bool(row.get::<_, Option<i64>>(13)?),
                        metric_key: row.get(14)?,
                        metric_before: row.get(15)?,
                        metric_after: row.get(16)?,
                        metric_delta: row.get(17)?,
                        target_metric: row.get(18)?,
                        floor_metric: row.get(19)?,
                        profile: row.get(20)?,
                        cloud_revision: row.get(21)?,
                        cloud_digest: row.get(22)?,
                        cost_estimate_usd: row.get(23)?,
                    })
                })?;
            let mut aggregate = Aggregate::default();
            for row in rows {
                aggregate.add(row?);
            }
            Ok(aggregate)
        })
        .map_err(|_| TelemetryError::Storage)?;
    Ok(aggregate.json(window, since_ms, generated_at_ms))
}

fn ensure_storage(db: &Db) -> Result<(), String> {
    db.with_immediate_transaction(|tx| {
        tx.execute_batch(
            "CREATE TABLE IF NOT EXISTS solver_telemetry_events (
                event_key TEXT PRIMARY KEY,
                source TEXT NOT NULL,
                executor TEXT NOT NULL,
                focus TEXT NOT NULL,
                gap_target TEXT NOT NULL,
                budget_kind TEXT NOT NULL,
                budget_seconds INTEGER NOT NULL,
                runtime_ms INTEGER,
                outcome TEXT NOT NULL,
                result_kind TEXT NOT NULL,
                fallback_kind TEXT NOT NULL,
                hard_valid INTEGER,
                applied INTEGER,
                target_reached INTEGER,
                floor_reached INTEGER,
                metric_key TEXT,
                metric_before INTEGER,
                metric_after INTEGER,
                metric_delta INTEGER,
                target_metric INTEGER,
                floor_metric INTEGER,
                profile TEXT,
                cloud_revision TEXT,
                cloud_digest TEXT,
                cost_estimate_usd REAL,
                started_at_ms INTEGER NOT NULL,
                completed_at_ms INTEGER,
                created_at_ms INTEGER NOT NULL
             );
             CREATE INDEX IF NOT EXISTS idx_solver_telemetry_created
                ON solver_telemetry_events(created_at_ms);
             CREATE INDEX IF NOT EXISTS idx_solver_telemetry_dimension
                ON solver_telemetry_events(executor, focus, outcome, created_at_ms);",
        )?;
        Ok(())
    })
    .map_err(|error| error.to_string())
}

fn insert_server_start(
    db: &Db,
    key: &str,
    metadata: &ServerRunMetadata,
    now_ms: u64,
) -> Result<(), String> {
    ensure_storage(db)?;
    let cutoff = now_ms.saturating_sub(RETENTION_MS);
    db.with_immediate_transaction(|tx| {
        tx.execute(
            "INSERT OR IGNORE INTO solver_telemetry_events \
             (event_key, source, executor, focus, gap_target, budget_kind, budget_seconds, \
              runtime_ms, outcome, result_kind, fallback_kind, hard_valid, applied, \
              target_reached, floor_reached, metric_key, metric_before, metric_after, \
              metric_delta, target_metric, floor_metric, profile, cloud_revision, cloud_digest, \
              cost_estimate_usd, started_at_ms, completed_at_ms, created_at_ms) \
             VALUES (?1, 'server', ?2, ?3, ?4, ?5, ?6, NULL, 'running', 'running', 'none', \
                     NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, ?7, NULL, ?8, \
                     NULL, ?9, NULL, ?9)",
            params![
                key,
                metadata.executor,
                metadata.focus,
                metadata.gap_target,
                metadata.budget_kind,
                sqlite_i64(metadata.budget_seconds),
                metadata.profile,
                metadata.cloud_digest,
                sqlite_i64(now_ms),
            ],
        )?;
        prune_storage(tx, cutoff)?;
        Ok(())
    })
    .map_err(|error| error.to_string())
}

fn finish_server_run(
    db: &Db,
    key: &str,
    runtime_ms: u64,
    facts: TerminalFacts,
    cost_estimate_usd: Option<f64>,
) -> Result<(), String> {
    let now_ms = now_millis();
    let cutoff = now_ms.saturating_sub(RETENTION_MS);
    db.with_immediate_transaction(|tx| {
        tx.execute(
            "UPDATE solver_telemetry_events SET \
               runtime_ms = ?2, outcome = ?3, result_kind = ?4, fallback_kind = ?5, \
               hard_valid = ?6, applied = ?7, target_reached = ?8, floor_reached = ?9, \
               metric_key = ?10, metric_before = ?11, metric_after = ?12, metric_delta = ?13, \
               target_metric = ?14, floor_metric = ?15, \
               cloud_revision = COALESCE(?16, cloud_revision), \
               cloud_digest = COALESCE(?17, cloud_digest), \
               cost_estimate_usd = ?18, completed_at_ms = ?19 \
             WHERE event_key = ?1",
            params![
                key,
                sqlite_i64(runtime_ms.min(MAX_RUNTIME_MS)),
                facts.outcome,
                facts.result_kind,
                facts.fallback,
                optional_bool_i64(facts.hard_valid),
                optional_bool_i64(facts.applied),
                optional_bool_i64(facts.target_reached),
                optional_bool_i64(facts.floor_reached),
                facts.metric_key,
                facts.metric_before,
                facts.metric_after,
                facts.metric_delta,
                facts.target_metric,
                facts.floor_metric,
                facts.cloud_revision,
                facts.cloud_digest,
                cost_estimate_usd.map(|value| value.clamp(0.0, MAX_COST_USD)),
                sqlite_i64(now_ms),
            ],
        )?;
        prune_storage(tx, cutoff)?;
        Ok(())
    })
    .map_err(|error| error.to_string())
}

fn event_exists(db: &Db, key: &str) -> Result<bool, String> {
    ensure_storage(db)?;
    db.with_immediate_transaction(|tx| {
        tx.query_row(
            "SELECT 1 FROM solver_telemetry_events WHERE event_key = ?1",
            [key],
            |_| Ok(()),
        )
        .optional()
        .map(|value| value.is_some())
    })
    .map_err(|error| error.to_string())
}

fn insert_browser_event(db: &Db, event: &BrowserFetEvent) -> Result<bool, String> {
    ensure_storage(db)?;
    let now_ms = now_millis();
    let cutoff = now_ms.saturating_sub(RETENTION_MS);
    db.with_immediate_transaction(|tx| {
        let changed = tx.execute(
            "INSERT OR IGNORE INTO solver_telemetry_events \
             (event_key, source, executor, focus, gap_target, budget_kind, budget_seconds, \
              runtime_ms, outcome, result_kind, fallback_kind, hard_valid, applied, \
              target_reached, floor_reached, metric_key, metric_before, metric_after, \
              metric_delta, target_metric, floor_metric, profile, cloud_revision, cloud_digest, \
              cost_estimate_usd, started_at_ms, completed_at_ms, created_at_ms) \
             VALUES (?1, 'browser', 'fet_web_worker', ?2, ?3, ?4, ?5, ?6, ?7, ?8, ?9, ?10, \
                     ?11, ?12, ?13, ?14, ?15, ?16, ?17, ?18, ?19, NULL, NULL, NULL, NULL, \
                     ?20, ?20, ?20)",
            params![
                event.key,
                event.focus,
                event.gap_target,
                event.budget_kind,
                sqlite_i64(event.budget_seconds),
                sqlite_i64(event.runtime_ms),
                event.outcome,
                event.result_kind,
                event.fallback,
                optional_bool_i64(event.hard_valid),
                optional_bool_i64(event.applied),
                optional_bool_i64(event.target_reached),
                optional_bool_i64(event.floor_reached),
                event.metric_key,
                event.metric_before,
                event.metric_after,
                event.metric_delta,
                event.target_metric,
                event.floor_metric,
                sqlite_i64(now_ms),
            ],
        )?;
        prune_storage(tx, cutoff)?;
        Ok(changed > 0)
    })
    .map_err(|error| error.to_string())
}

fn prune_storage(tx: &rusqlite::Transaction<'_>, cutoff_ms: u64) -> rusqlite::Result<()> {
    tx.execute(
        "DELETE FROM solver_telemetry_events WHERE created_at_ms < ?1",
        [sqlite_i64(cutoff_ms)],
    )?;
    tx.execute(
        "DELETE FROM solver_telemetry_events WHERE event_key IN (
            SELECT event_key FROM solver_telemetry_events
            ORDER BY created_at_ms ASC, event_key ASC
            LIMIT (SELECT CASE WHEN COUNT(*) > ?1 THEN COUNT(*) - ?1 ELSE 0 END
                   FROM solver_telemetry_events)
         )",
        [MAX_EVENT_ROWS],
    )?;
    Ok(())
}

fn canonical_focus(settings: Option<&Map<String, Value>>) -> (String, String) {
    let setting = |name: &str| {
        settings
            .and_then(|map| map.get(name))
            .and_then(Value::as_str)
    };
    let mode = setting("ui_requested_solve_mode")
        .or_else(|| setting("optimization_focus_mode"))
        .or_else(|| setting("optimization_focus"))
        .unwrap_or("automatic");
    let normalized = normalize_word(mode);
    let raw_gap_target = setting("optimization_gap_target")
        .or_else(|| setting("ui_requested_gap_target"))
        .unwrap_or("");
    let gap_target = match normalize_word(raw_gap_target).as_str() {
        "gap1" | "teacher_gap1_sessions" | "optimize_gap1" => "gap1",
        "gap2" | "teacher_gap2_sessions" | "optimize_gap2" => "gap2",
        _ => "",
    };
    match normalized.as_str() {
        "optimize_singletons" | "singleton" | "singletons" | "one_period_teacher_sessions" => {
            ("singletons".to_string(), "".to_string())
        }
        "optimize_sessions" | "session" | "sessions" | "teacher_sessions" => {
            ("sessions".to_string(), "".to_string())
        }
        "optimize_gap1" | "gap1" | "teacher_gap1_sessions" => {
            ("gaps".to_string(), "gap1".to_string())
        }
        "optimize_gap2" | "gap2" | "teacher_gap2_sessions" => {
            ("gaps".to_string(), "gap2".to_string())
        }
        "optimize_gaps" | "gap" | "gaps" | "teacher_gaps" => {
            ("gaps".to_string(), gap_target.to_string())
        }
        _ => ("automatic".to_string(), "".to_string()),
    }
}

fn canonical_budget(executor: &str, settings: Option<&Map<String, Value>>) -> (String, u64) {
    let setting = |name: &str| settings.and_then(|map| map.get(name));
    if executor == "cloud_run" {
        let deep = setting("ui_hybrid_deep_optimize")
            .and_then(value_bool)
            .unwrap_or(false);
        return if deep {
            ("deep".to_string(), 180)
        } else {
            ("standard".to_string(), 60)
        };
    }
    let seconds = setting("overall_time_limit_seconds")
        .and_then(value_u64)
        .or_else(|| setting("optimization_time_limit_seconds").and_then(value_u64))
        .or_else(|| {
            setting("backend_deadline_ms")
                .and_then(value_u64)
                .map(|value| value / 1_000)
        })
        .unwrap_or(0)
        .min(1_800);
    ("server".to_string(), seconds)
}

fn canonical_browser_focus(focus: &str, gap_target: Option<&str>) -> Option<(String, String)> {
    match focus {
        "automatic" => gap_target
            .is_none()
            .then(|| ("automatic".to_string(), "".to_string())),
        "singletons" => gap_target
            .is_none()
            .then(|| ("singletons".to_string(), "".to_string())),
        "sessions" => gap_target
            .is_none()
            .then(|| ("sessions".to_string(), "".to_string())),
        "gaps" => match gap_target {
            Some("gap1") => Some(("gaps".to_string(), "gap1".to_string())),
            Some("gap2") => Some(("gaps".to_string(), "gap2".to_string())),
            _ => None,
        },
        _ => None,
    }
}

fn canonical_metric_key(focus: &str, gap_target: &str) -> Option<String> {
    match (focus, gap_target) {
        ("singletons", "") => Some("singletons".to_string()),
        ("sessions", "") => Some("sessions".to_string()),
        ("gaps", "gap1") => Some("gap1".to_string()),
        ("gaps", "gap2") => Some("gap2".to_string()),
        _ => None,
    }
}

fn metric_baseline_setting(settings: Option<&Map<String, Value>>, key: &str) -> Option<i64> {
    let settings = settings?;
    let name = match key {
        "gap1" => "ui_progress_gap1_baseline",
        "gap2" => "ui_progress_gap2_baseline",
        "singletons" | "sessions" => "ui_progress_metric_baseline",
        _ => return None,
    };
    settings.get(name).and_then(nonnegative_metric)
}

fn metric_target_setting(settings: Option<&Map<String, Value>>, key: &str) -> Option<i64> {
    let settings = settings?;
    match key {
        "sessions" => settings
            .get("ui_progress_metric_target")
            .or_else(|| settings.get("target_teacher_sessions"))
            .and_then(nonnegative_metric),
        "singletons" | "gap1" | "gap2" => Some(0),
        _ => None,
    }
}

fn metric_value(metrics: Option<&Value>, key: &str) -> Option<i64> {
    let metrics = metrics?.as_object()?;
    match key {
        "singletons" => metrics
            .get("one_period_teacher_sessions")
            .or_else(|| metrics.get("soBuoiDay1"))
            .and_then(nonnegative_metric),
        "sessions" => metrics
            .get("teacher_sessions")
            .or_else(|| metrics.get("tsBuoiDay"))
            .and_then(nonnegative_metric),
        "gap2" => metrics
            .get("teacher_gap2_sessions")
            .or_else(|| metrics.get("soBuoiTrong2"))
            .and_then(nonnegative_metric)
            .or_else(|| gap_distribution_value(metrics, 2)),
        "gap1" => metrics
            .get("teacher_gap1_sessions")
            .or_else(|| metrics.get("soBuoiTrong1"))
            .and_then(nonnegative_metric)
            .or_else(|| gap_distribution_value(metrics, 1)),
        _ => None,
    }
}

fn metric_baseline_value(payload: Option<&Value>, key: &str) -> Option<i64> {
    let payload = payload?;
    let metrics = payload.get("metrics")?.as_object()?;
    let named = match key {
        "singletons" => "one_period_teacher_sessions_baseline",
        "sessions" => "teacher_sessions_baseline",
        "gap1" => "teacher_gap1_sessions_baseline",
        "gap2" => "teacher_gap2_sessions_baseline",
        _ => return None,
    };
    metrics.get(named).and_then(nonnegative_metric)
}

fn metric_floor_value(metrics: Option<&Value>, key: &str) -> Option<i64> {
    let metrics = metrics?.as_object()?;
    let named = match key {
        "singletons" => "one_period_teacher_sessions_lower_bound",
        "sessions" => "teacher_sessions_lower_bound",
        "gap1" => "teacher_gap1_sessions_lower_bound",
        "gap2" => "teacher_gap2_sessions_lower_bound",
        _ => return None,
    };
    metrics.get(named).and_then(nonnegative_metric)
}

fn inferred_hard_valid(payload: Option<&Value>) -> Option<bool> {
    let metrics = payload?.get("metrics")?.as_object()?;
    let hard_ok = metrics.get("hard_ok").and_then(value_bool)?;
    let core_hard_ok = metrics.get("core_hard_ok").and_then(value_bool)?;
    let no_conflicts = [
        "class_slot_conflicts",
        "teacher_slot_conflicts",
        "room_slot_conflicts",
        "app_constraint_violation_count",
    ]
    .iter()
    .all(|key| metrics.get(*key).and_then(nonnegative_metric) == Some(0));
    Some(hard_ok && core_hard_ok && no_conflicts)
}

fn gap_distribution_value(metrics: &Map<String, Value>, minimum: i64) -> Option<i64> {
    let distribution = metrics.get("gap_distribution")?.as_object()?;
    let mut total = 0_i64;
    let mut found = false;
    for (gap, count) in distribution {
        let Ok(gap) = gap.parse::<i64>() else {
            continue;
        };
        if gap >= minimum {
            total = total.checked_add(nonnegative_metric(count)?)?;
            found = true;
        }
    }
    found.then_some(total)
}

fn bool_from_paths(payload: Option<&Value>, paths: &[&[&str]]) -> Option<bool> {
    let payload = payload?;
    paths.iter().find_map(|path| {
        let mut value = payload;
        for key in *path {
            value = value.get(*key)?;
        }
        value_bool(value)
    })
}

fn runtime_string<'a>(payload: &'a Value, key: &str) -> Option<&'a str> {
    payload
        .get("solver")
        .and_then(|solver| solver.get("runtime_settings"))
        .and_then(|runtime| runtime.get(key))
        .and_then(Value::as_str)
}

fn normalize_executor(value: &str) -> Option<&'static str> {
    match value {
        "cloud_run" => Some("cloud_run"),
        "vps" => Some("vps"),
        "fet_web_worker" => Some("fet_web_worker"),
        _ => None,
    }
}

fn normalize_outcome(value: &str) -> String {
    match value {
        "completed" => "completed",
        "failed" => "failed",
        "cancelled" => "cancelled",
        "released" => "released",
        "timeout" => "timeout",
        "no_improvement" => "no_improvement",
        "infeasible" => "infeasible",
        _ => "failed",
    }
    .to_string()
}

fn browser_outcome(value: &str) -> Option<String> {
    matches!(
        value,
        "completed" | "failed" | "cancelled" | "timeout" | "no_improvement" | "infeasible"
    )
    .then(|| value.to_string())
}

fn normalize_result_kind(value: &str) -> String {
    let normalized = normalize_word(value);
    if normalized.contains("cancel") {
        "cancelled"
    } else if normalized.contains("timeout") || normalized.contains("deadline") {
        "timeout"
    } else if normalized.contains("infeasible") || normalized.contains("capacity") {
        "infeasible"
    } else if normalized.contains("pareto") || normalized.contains("improvement") {
        "no_improvement"
    } else if normalized.contains("valid") || normalized.contains("candidate") {
        "invalid_candidate"
    } else if normalized.contains("panic") {
        "panic"
    } else if normalized.contains("serverless")
        || normalized.contains("cloud")
        || normalized.contains("transport")
    {
        "transport_error"
    } else if normalized.is_empty() || normalized == "completed" || normalized == "ok" {
        "completed"
    } else {
        "other"
    }
    .to_string()
}

fn browser_result_kind(value: &str) -> Option<String> {
    matches!(
        value,
        "completed"
            | "failed"
            | "cancelled"
            | "timeout"
            | "infeasible"
            | "no_improvement"
            | "invalid_candidate"
            | "hard_constraint_violation"
            | "preflight_infeasible"
            | "budget_exhausted"
    )
    .then(|| value.to_string())
}

fn normalize_fallback(value: &str) -> String {
    match value {
        "none" | "vps" | "cloud_run" | "agent" | "coordinator_exit" | "cloud_run_failed"
        | "user_selected_fet" | "retry_local" | "keep_incumbent" | "not_applicable" => {
            value.to_string()
        }
        _ => "other".to_string(),
    }
}

fn browser_fallback(value: &str) -> Result<String, ()> {
    matches!(
        value,
        "none"
            | "cloud_run_failed"
            | "user_selected_fet"
            | "retry_local"
            | "keep_incumbent"
            | "not_applicable"
            | "coordinator_exit"
    )
    .then(|| value.to_string())
    .ok_or(())
}

fn normalize_word(value: &str) -> String {
    value
        .trim()
        .to_ascii_lowercase()
        .replace('-', "_")
        .replace(' ', "_")
}

fn sanitize_profile(value: &str) -> Option<String> {
    sanitize_token(value, 80)
}

fn sanitize_revision(value: &str) -> Option<String> {
    sanitize_token(value, 120)
}

fn sanitize_digest(value: &str) -> Option<String> {
    let value = value.trim().to_ascii_lowercase();
    (value.len() == 64 && value.bytes().all(|byte| byte.is_ascii_hexdigit())).then_some(value)
}

fn sanitize_token(value: &str, max_len: usize) -> Option<String> {
    let value = value.trim();
    (!value.is_empty()
        && value.len() <= max_len
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.')))
    .then(|| value.to_string())
}

fn valid_opaque_event_id(value: &str) -> bool {
    value.len() >= 16
        && value.len() <= 128
        && value
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'_' | b'-' | b'.' | b':'))
}

fn string_field<'a>(object: &'a Map<String, Value>, key: &str) -> Result<&'a str, TelemetryError> {
    object
        .get(key)
        .and_then(Value::as_str)
        .filter(|value| !value.is_empty() && value.len() <= 128)
        .ok_or(TelemetryError::Invalid)
}

fn optional_string_field<'a>(
    object: &'a Map<String, Value>,
    key: &str,
) -> Result<Option<&'a str>, TelemetryError> {
    match object.get(key) {
        None | Some(Value::Null) => Ok(None),
        Some(Value::String(value)) if !value.is_empty() && value.len() <= 128 => Ok(Some(value)),
        _ => Err(TelemetryError::Invalid),
    }
}

fn unsigned_field(object: &Map<String, Value>, key: &str) -> Result<u64, TelemetryError> {
    object
        .get(key)
        .and_then(Value::as_u64)
        .ok_or(TelemetryError::Invalid)
}

fn optional_bool_field(
    object: &Map<String, Value>,
    key: &str,
) -> Result<Option<bool>, TelemetryError> {
    match object.get(key) {
        None | Some(Value::Null) => Ok(None),
        Some(Value::Bool(value)) => Ok(Some(*value)),
        _ => Err(TelemetryError::Invalid),
    }
}

fn optional_nonnegative_metric(
    object: &Map<String, Value>,
    key: &str,
) -> Result<Option<i64>, TelemetryError> {
    match object.get(key) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => nonnegative_metric(value)
            .ok_or(TelemetryError::Invalid)
            .map(Some),
    }
}

fn optional_signed_metric(
    object: &Map<String, Value>,
    key: &str,
) -> Result<Option<i64>, TelemetryError> {
    match object.get(key) {
        None | Some(Value::Null) => Ok(None),
        Some(value) => value
            .as_i64()
            .filter(|number| number.unsigned_abs() <= MAX_METRIC_VALUE as u64)
            .ok_or(TelemetryError::Invalid)
            .map(Some),
    }
}

fn nonnegative_metric(value: &Value) -> Option<i64> {
    value
        .as_i64()
        .or_else(|| value.as_u64().and_then(|number| i64::try_from(number).ok()))
        .filter(|number| (0..=MAX_METRIC_VALUE).contains(number))
}

fn value_u64(value: &Value) -> Option<u64> {
    value
        .as_u64()
        .or_else(|| value.as_i64().and_then(|number| u64::try_from(number).ok()))
}

fn value_bool(value: &Value) -> Option<bool> {
    match value {
        Value::Bool(value) => Some(*value),
        Value::Number(value) => value.as_i64().map(|value| value != 0),
        Value::String(value) => match value.trim().to_ascii_lowercase().as_str() {
            "1" | "true" | "yes" | "on" => Some(true),
            "0" | "false" | "no" | "off" => Some(false),
            _ => None,
        },
        _ => None,
    }
}

fn optional_bool_i64(value: Option<bool>) -> Option<i64> {
    value.map(|value| if value { 1 } else { 0 })
}

fn nullable_bool(value: Option<i64>) -> Option<bool> {
    value.map(|value| value != 0)
}

fn nonnegative_u64(value: i64) -> u64 {
    value.max(0) as u64
}

fn nullable_nonnegative_u64(value: Option<i64>) -> Option<u64> {
    value.map(nonnegative_u64)
}

fn sqlite_i64(value: u64) -> i64 {
    value.min(i64::MAX as u64) as i64
}

fn now_millis() -> u64 {
    SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .map(|value| value.as_millis().min(u64::MAX as u128) as u64)
        .unwrap_or(0)
}

fn digest_event_id(domain: &str, value: &str) -> String {
    let mut hasher = Sha256::new();
    hasher.update(b"tkb-solver-telemetry-v1\0");
    hasher.update(domain.as_bytes());
    hasher.update(b"\0");
    hasher.update(value.as_bytes());
    hasher
        .finalize()
        .iter()
        .map(|byte| format!("{byte:02x}"))
        .collect()
}

fn generated_event_key() -> String {
    // OS CSPRNG-backed token from the authentication module is held only while
    // creating this hash.  The raw token never crosses an API or database
    // boundary.
    digest_event_id("server", &crate::auth::random_token())
}

#[derive(Default)]
struct FetRateLimiter {
    buckets: Mutex<HashMap<String, RateBucket>>,
}

#[derive(Clone, Copy)]
struct RateBucket {
    window_started_ms: u64,
    count: u32,
    touched_ms: u64,
}

impl FetRateLimiter {
    fn allow(&self, actor_key: &str, client_ip: &str, now_ms: u64) -> bool {
        let bucket_key = digest_event_id("fet-rate", &format!("{actor_key}\0{client_ip}"));
        let Ok(mut buckets) = self.buckets.lock() else {
            // Failing closed here prevents a mutex poisoning event from making
            // the endpoint an unbounded write primitive.
            return false;
        };
        let stale_before = now_ms.saturating_sub(RATE_WINDOW_MS.saturating_mul(2));
        if buckets.len() > 4_096 {
            buckets.retain(|_, bucket| bucket.touched_ms >= stale_before);
        }
        let bucket = buckets.entry(bucket_key).or_insert(RateBucket {
            window_started_ms: now_ms,
            count: 0,
            touched_ms: now_ms,
        });
        if now_ms.saturating_sub(bucket.window_started_ms) >= RATE_WINDOW_MS {
            bucket.window_started_ms = now_ms;
            bucket.count = 0;
        }
        bucket.touched_ms = now_ms;
        if bucket.count >= FET_EVENTS_PER_WINDOW {
            return false;
        }
        bucket.count += 1;
        true
    }
}

fn fet_rate_limiter() -> &'static FetRateLimiter {
    static LIMITER: OnceLock<FetRateLimiter> = OnceLock::new();
    LIMITER.get_or_init(FetRateLimiter::default)
}

#[derive(Clone)]
struct TelemetryRow {
    source: String,
    executor: String,
    focus: String,
    gap_target: String,
    budget_kind: String,
    budget_seconds: u64,
    runtime_ms: Option<u64>,
    outcome: String,
    result_kind: String,
    fallback: String,
    hard_valid: Option<bool>,
    applied: Option<bool>,
    target_reached: Option<bool>,
    floor_reached: Option<bool>,
    metric_key: Option<String>,
    metric_before: Option<i64>,
    metric_after: Option<i64>,
    metric_delta: Option<i64>,
    target_metric: Option<i64>,
    floor_metric: Option<i64>,
    profile: Option<String>,
    cloud_revision: Option<String>,
    cloud_digest: Option<String>,
    cost_estimate_usd: Option<f64>,
}

#[derive(Default, Clone)]
struct AggregateDimension {
    total: u64,
    terminal: u64,
    completed: u64,
    failed: u64,
    cancelled: u64,
    released: u64,
    timeout: u64,
    no_improvement: u64,
    infeasible: u64,
    running: u64,
    hard_valid_known: u64,
    hard_valid_true: u64,
    applied_known: u64,
    applied_true: u64,
    target_known: u64,
    target_true: u64,
    floor_known: u64,
    floor_true: u64,
    metric_samples: u64,
    metric_delta_sum: i64,
    metric_before_sum: i64,
    metric_after_sum: i64,
    target_metric_samples: u64,
    target_metric_sum: i64,
    floor_metric_samples: u64,
    floor_metric_sum: i64,
    cost_estimate_usd: f64,
    runtimes: Vec<u64>,
}

impl AggregateDimension {
    fn add(&mut self, row: &TelemetryRow) {
        self.total += 1;
        match row.outcome.as_str() {
            "running" => self.running += 1,
            "completed" => {
                self.terminal += 1;
                self.completed += 1;
            }
            "failed" => {
                self.terminal += 1;
                self.failed += 1;
            }
            "cancelled" => {
                self.terminal += 1;
                self.cancelled += 1;
            }
            "released" => {
                self.terminal += 1;
                self.released += 1;
            }
            "timeout" => {
                self.terminal += 1;
                self.timeout += 1;
            }
            "no_improvement" => {
                self.terminal += 1;
                self.no_improvement += 1;
            }
            "infeasible" => {
                self.terminal += 1;
                self.infeasible += 1;
            }
            _ => {
                self.terminal += 1;
                self.failed += 1;
            }
        }
        if let Some(runtime) = row.runtime_ms {
            self.runtimes.push(runtime);
        }
        bool_count(
            row.hard_valid,
            &mut self.hard_valid_known,
            &mut self.hard_valid_true,
        );
        bool_count(row.applied, &mut self.applied_known, &mut self.applied_true);
        bool_count(
            row.target_reached,
            &mut self.target_known,
            &mut self.target_true,
        );
        bool_count(
            row.floor_reached,
            &mut self.floor_known,
            &mut self.floor_true,
        );
        if let Some(delta) = row.metric_delta {
            self.metric_samples += 1;
            self.metric_delta_sum = self.metric_delta_sum.saturating_add(delta);
            self.metric_before_sum = self
                .metric_before_sum
                .saturating_add(row.metric_before.unwrap_or(0));
            self.metric_after_sum = self
                .metric_after_sum
                .saturating_add(row.metric_after.unwrap_or(0));
        }
        if let Some(target) = row.target_metric {
            self.target_metric_samples += 1;
            self.target_metric_sum = self.target_metric_sum.saturating_add(target);
        }
        if let Some(floor) = row.floor_metric {
            self.floor_metric_samples += 1;
            self.floor_metric_sum = self.floor_metric_sum.saturating_add(floor);
        }
        self.cost_estimate_usd += row.cost_estimate_usd.unwrap_or(0.0).max(0.0);
    }

    fn json(&self) -> Value {
        let p50 = percentile(&self.runtimes, 0.50);
        let p95 = percentile(&self.runtimes, 0.95);
        json!({
            "total": self.total,
            "terminal": self.terminal,
            "completed": self.completed,
            "failed": self.failed,
            "cancelled": self.cancelled,
            "released": self.released,
            "timeout": self.timeout,
            "noImprovement": self.no_improvement,
            "infeasible": self.infeasible,
            "running": self.running,
            "successRate": percentage(self.completed, self.terminal),
            "hardValidRate": percentage(self.hard_valid_true, self.hard_valid_known),
            "appliedRate": percentage(self.applied_true, self.applied_known),
            "targetReachedRate": percentage(self.target_true, self.target_known),
            "floorReachedRate": percentage(self.floor_true, self.floor_known),
            "runtimeMs": {"samples": self.runtimes.len(), "p50": p50, "p95": p95},
            "metric": {
                "samples": self.metric_samples,
                "deltaSum": self.metric_delta_sum,
                "deltaAverage": if self.metric_samples == 0 { Value::Null } else { json!(round2(self.metric_delta_sum as f64 / self.metric_samples as f64)) },
                "beforeSum": self.metric_before_sum,
                "afterSum": self.metric_after_sum,
                "targetSamples": self.target_metric_samples,
                "targetSum": self.target_metric_sum,
                "floorSamples": self.floor_metric_samples,
                "floorSum": self.floor_metric_sum
            },
            "estimatedCostUsd": round6(self.cost_estimate_usd)
        })
    }
}

fn bool_count(value: Option<bool>, known: &mut u64, true_count: &mut u64) {
    if let Some(value) = value {
        *known += 1;
        if value {
            *true_count += 1;
        }
    }
}

#[derive(Default)]
struct Aggregate {
    overall: AggregateDimension,
    by_executor: BTreeMap<String, AggregateDimension>,
    by_focus: BTreeMap<String, AggregateDimension>,
    by_executor_focus_budget: BTreeMap<(String, String, String, String, u64), AggregateDimension>,
    by_outcome: BTreeMap<String, AggregateDimension>,
    by_result_kind: BTreeMap<String, AggregateDimension>,
    by_fallback: BTreeMap<String, AggregateDimension>,
    by_budget: BTreeMap<String, AggregateDimension>,
    by_metric: BTreeMap<String, AggregateDimension>,
    cloud_dimensions: BTreeMap<(String, String, String), AggregateDimension>,
    browser_events: u64,
    server_events: u64,
    deep_runs: u64,
}

impl Aggregate {
    fn add(&mut self, row: TelemetryRow) {
        self.overall.add(&row);
        self.by_executor
            .entry(row.executor.clone())
            .or_default()
            .add(&row);
        let focus_key = if row.gap_target.is_empty() {
            row.focus.clone()
        } else {
            format!("{}:{}", row.focus, row.gap_target)
        };
        self.by_focus.entry(focus_key).or_default().add(&row);
        self.by_executor_focus_budget
            .entry((
                row.executor.clone(),
                row.focus.clone(),
                row.gap_target.clone(),
                row.budget_kind.clone(),
                row.budget_seconds,
            ))
            .or_default()
            .add(&row);
        self.by_outcome
            .entry(row.outcome.clone())
            .or_default()
            .add(&row);
        self.by_result_kind
            .entry(row.result_kind.clone())
            .or_default()
            .add(&row);
        self.by_fallback
            .entry(row.fallback.clone())
            .or_default()
            .add(&row);
        self.by_budget
            .entry(format!("{}:{}s", row.budget_kind, row.budget_seconds))
            .or_default()
            .add(&row);
        if let Some(metric_key) = row.metric_key.clone() {
            self.by_metric.entry(metric_key).or_default().add(&row);
        }
        if row.source == "browser" {
            self.browser_events += 1;
        } else {
            self.server_events += 1;
        }
        if row.budget_kind == "deep" {
            self.deep_runs += 1;
        }
        if row.executor == "cloud_run" {
            let profile = row.profile.clone().unwrap_or_else(|| "unknown".to_string());
            let revision = row
                .cloud_revision
                .clone()
                .unwrap_or_else(|| "unknown".to_string());
            let digest = row
                .cloud_digest
                .clone()
                .unwrap_or_else(|| "unknown".to_string());
            self.cloud_dimensions
                .entry((profile, revision, digest))
                .or_default()
                .add(&row);
        }
    }

    fn json(self, window: &str, since_ms: u64, generated_at_ms: u64) -> Value {
        let total = self.overall.total;
        let cloud_dimensions = self
            .cloud_dimensions
            .into_iter()
            .map(|((profile, revision, digest), dimension)| {
                json!({
                    "profile": profile,
                    "revision": revision,
                    "digest": digest,
                    "aggregate": dimension.json()
                })
            })
            .collect::<Vec<_>>();
        let by_executor_focus_budget = self
            .by_executor_focus_budget
            .into_iter()
            .map(|((executor, focus, gap_target, budget_kind, budget_seconds), dimension)| {
                json!({
                    "executor": executor,
                    "focus": focus,
                    "gapTarget": if gap_target.is_empty() { Value::Null } else { json!(gap_target) },
                    "budgetKind": budget_kind,
                    "budgetSeconds": budget_seconds,
                    "aggregate": dimension.json()
                })
            })
            .collect::<Vec<_>>();
        json!({
            "ok": true,
            "window": window,
            "sinceMs": since_ms,
            "generatedAtMs": generated_at_ms,
            "retentionDays": RETENTION_MS / (24 * 60 * 60 * 1_000),
            "privacy": {
                "aggregateOnly": true,
                "doesNotStore": ["timetable", "request", "schoolId", "accountId", "userId", "rawError", "rawEventId"]
            },
            "events": {"total": total, "browser": self.browser_events, "server": self.server_events},
            "deepRunRate": percentage(self.deep_runs, total),
            "overall": self.overall.json(),
            "byExecutor": dimensions_json(self.by_executor),
            "byFocus": dimensions_json(self.by_focus),
            "byExecutorFocusBudget": by_executor_focus_budget,
            "byOutcome": dimensions_json(self.by_outcome),
            "byResultKind": dimensions_json(self.by_result_kind),
            "byFallback": dimensions_json(self.by_fallback),
            "byBudget": dimensions_json(self.by_budget),
            "byMetric": dimensions_json(self.by_metric),
            "cloud": cloud_dimensions
        })
    }
}

fn dimensions_json(dimensions: BTreeMap<String, AggregateDimension>) -> Vec<Value> {
    dimensions
        .into_iter()
        .map(|(key, dimension)| json!({"key": key, "aggregate": dimension.json()}))
        .collect()
}

fn percentile(values: &[u64], percentile: f64) -> Value {
    if values.is_empty() {
        return Value::Null;
    }
    let mut values = values.to_vec();
    values.sort_unstable();
    let rank = ((values.len() as f64 * percentile).ceil() as usize).saturating_sub(1);
    json!(values[rank.min(values.len().saturating_sub(1))])
}

fn percentage(numerator: u64, denominator: u64) -> Value {
    if denominator == 0 {
        Value::Null
    } else {
        json!(round2(numerator as f64 * 100.0 / denominator as f64))
    }
}

fn round2(value: f64) -> f64 {
    (value * 100.0).round() / 100.0
}

fn round6(value: f64) -> f64 {
    (value * 1_000_000.0).round() / 1_000_000.0
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn memory_db() -> Db {
        Db::new(PathBuf::from(":memory:")).expect("in-memory database")
    }

    fn fet_body(event_id: &str) -> Vec<u8> {
        serde_json::to_vec(&json!({
            "eventId": event_id,
            "executor": "fet_web_worker",
            "focus": "gaps",
            "gapTarget": "gap2",
            "budgetKind": "local",
            "budgetSeconds": 12,
            "runtimeMs": 321,
            "outcome": "completed",
            "resultKind": "completed",
            "fallback": "none",
            "hardValid": true,
            "applied": true,
            "targetReached": false,
            "floorReached": true,
            "metricKey": "gap2",
            "metricBefore": 9,
            "metricAfter": 4,
            "metricDelta": 5,
            "targetMetric": 0,
            "floorMetric": 4
        }))
        .expect("FET body")
    }

    #[test]
    fn browser_fet_event_is_idempotent_and_aggregate_only() {
        let db = memory_db();
        let body = fet_body("fet-event-00000001");
        assert_eq!(
            record_browser_fet_event(&db, "session-one", "127.0.0.1", &body).unwrap(),
            true
        );
        assert_eq!(
            record_browser_fet_event(&db, "session-one", "127.0.0.1", &body).unwrap(),
            false
        );
        let aggregate = aggregate_for_window(&db, "24h").expect("aggregate");
        assert_eq!(aggregate["events"]["total"], json!(1));
        assert_eq!(aggregate["events"]["browser"], json!(1));
        assert_eq!(aggregate["byExecutor"][0]["key"], json!("fet_web_worker"));
        assert_eq!(
            aggregate["byExecutorFocusBudget"][0]["executor"],
            json!("fet_web_worker")
        );
        assert_eq!(
            aggregate["byExecutorFocusBudget"][0]["budgetSeconds"],
            json!(12)
        );
        assert_eq!(aggregate["overall"]["metric"]["deltaSum"], json!(5));
        assert_eq!(aggregate["privacy"]["aggregateOnly"], json!(true));

        let raw_event_id: String = db
            .with_immediate_transaction(|tx| {
                tx.query_row(
                    "SELECT event_key FROM solver_telemetry_events LIMIT 1",
                    [],
                    |row| row.get(0),
                )
            })
            .expect("stored event key");
        assert_ne!(raw_event_id, "fet-event-00000001");
        assert_eq!(raw_event_id.len(), 64);
    }

    #[test]
    fn browser_fet_rejects_raw_error_fields_and_metric_lies() {
        let db = memory_db();
        let mut value: Value = serde_json::from_slice(&fet_body("fet-event-00000002")).unwrap();
        value["error"] = json!("teacher private information");
        assert!(matches!(
            record_browser_fet_event(
                &db,
                "session-two",
                "127.0.0.1",
                &serde_json::to_vec(&value).unwrap()
            ),
            Err(TelemetryError::Invalid)
        ));
        value.as_object_mut().unwrap().remove("error");
        value["metricDelta"] = json!(99);
        assert!(matches!(
            record_browser_fet_event(
                &db,
                "session-two",
                "127.0.0.1",
                &serde_json::to_vec(&value).unwrap()
            ),
            Err(TelemetryError::Invalid)
        ));
    }

    #[test]
    fn server_events_keep_cloud_metadata_but_not_request_data() {
        let db = Arc::new(memory_db());
        let request = json!({
            "data": {"lop": [{"ten":"must not persist"}]},
            "settings": {
                "ui_requested_solve_mode":"optimize_gap2",
                "optimization_focus":"gaps",
                "optimization_gap_target":"gap2",
                "ui_hybrid_deep_optimize":true
            }
        });
        let metadata = ServerRunMetadata::from_request(
            "cloud_run",
            Some(&request),
            Some("primary-cloud"),
            Some("aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"),
        );
        assert_eq!(metadata.focus, "gaps");
        assert_eq!(metadata.gap_target, "gap2");
        assert_eq!(metadata.budget_kind, "deep");
        let mut run = ServerRun::start(Arc::clone(&db), metadata);
        run.finish(
            "completed",
            Some(&json!({
                "kind":"completed",
                "hardValid":true,
                "applied":true,
                "targetReached":true,
                "metrics":{"teacher_gap2_sessions":0},
                "solver":{"runtime_settings":{
                    "cloud_revision":"tkb-solver-00004-abc",
                    "cloud_solver_digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
                }}
            })),
            Some("none"),
            Some(0.0123456),
        );
        let aggregate = aggregate_for_window(&db, "24h").expect("aggregate");
        assert_eq!(aggregate["events"]["server"], json!(1));
        assert_eq!(aggregate["cloud"][0]["profile"], json!("primary-cloud"));
        assert_eq!(
            aggregate["cloud"][0]["revision"],
            json!("tkb-solver-00004-abc")
        );
        assert_eq!(
            aggregate["cloud"][0]["aggregate"]["estimatedCostUsd"],
            json!(0.012346)
        );
    }

    #[test]
    fn canonical_server_context_clamps_cloud_budget_labels() {
        let standard = ServerRunMetadata::from_request(
            "cloud_run",
            Some(
                &json!({"settings":{"ui_hybrid_deep_optimize":false, "optimization_focus":"singletons"}}),
            ),
            None,
            None,
        );
        assert_eq!(standard.budget_kind, "standard");
        assert_eq!(standard.budget_seconds, 60);
        let deep = ServerRunMetadata::from_request(
            "cloud_run",
            Some(
                &json!({"settings":{"ui_hybrid_deep_optimize":true, "optimization_focus":"gaps", "optimization_gap_target":"gap1"}}),
            ),
            None,
            None,
        );
        assert_eq!(deep.budget_kind, "deep");
        assert_eq!(deep.budget_seconds, 180);
        assert_eq!(deep.gap_target, "gap1");
    }

    #[test]
    fn fet_rate_limiter_is_bounded_and_resets_next_window() {
        let limiter = FetRateLimiter::default();
        for _ in 0..FET_EVENTS_PER_WINDOW {
            assert!(limiter.allow("session-rate", "127.0.0.1", 10_000));
        }
        assert!(!limiter.allow("session-rate", "127.0.0.1", 10_000));
        assert!(limiter.allow("session-rate", "127.0.0.1", 10_000 + RATE_WINDOW_MS));
    }
}
