const fs = require('fs');

// Load engine and phanmon logic
const engineCode = fs.readFileSync("C:/Users/Love/Documents/Codex/TKBCherry/web/tkb-fet-engine.js", 'utf8');
const dataJson = JSON.parse(fs.readFileSync("C:/Users/Love/Documents/Codex/temp/school_default.json", 'utf8'));

eval(engineCode);

console.log("=== CHECKING TOTAL LESSON COUNT IN PCCM VS TKB ===");
const pccmTiet = dataJson.pccmTietMatrix || {};
const tkb = dataJson.tkb || {};
const lopList = dataJson.lop || [];

let totalPccmPeriods = 0;
for(const [k, v] of Object.entries(pccmTiet)){
  totalPccmPeriods += Number(v || 0);
}
console.log("Total periods in pccmTietMatrix:", totalPccmPeriods);

let totalTkbCells = 0;
const days = ["thu2", "thu3", "thu4", "thu5", "thu6", "thu7"];
const sessions = ["sang", "chieu"];

for(const [cid, cData] of Object.entries(tkb)){
  for(const d of days){
    for(const s of sessions){
      const cells = (cData[d] && cData[d][s]) || [];
      for(const c of cells){
        if(c && c !== "OFF"){
          totalTkbCells++;
        }
      }
    }
  }
}
console.log("Total occupied cells in DATA.tkb:", totalTkbCells);

// Test engine load and snapshot
const engine = new FetTimetableEngine(dataJson, { gap2SessionBudget: 20 });
engine.init();
engine.loadExistingSchedule();

console.log("Engine total activities created:", engine.activities.length);
let placedCount = 0;
for(let i = 0; i < engine.activities.length; i++){
  if(engine.actPlacement[i] >= 0) placedCount++;
}
console.log("Engine placed activities on load:", placedCount);
console.log("Engine initial metrics:", engine.evaluateMetrics());

// Check snapshot TKB generated by engine
const snapshotTkb = engine.getSnapshotTKB();
let snapshotCells = 0;
for(const [cid, cData] of Object.entries(snapshotTkb)){
  for(const d of days){
    for(const s of sessions){
      const cells = (cData[d] && cData[d][s]) || [];
      for(const c of cells){
        if(c && c !== "OFF"){
          snapshotCells++;
        }
      }
    }
  }
}
console.log("Total occupied cells in Engine Snapshot TKB:", snapshotCells);
