steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --file
      - tools/cloud-run/Dockerfile
      - --build-arg
      - TKB_SOLVER_DIGEST=${_SOLVER_DIGEST}
      - --tag
      - ${_IMAGE}
      - .
images:
  - ${_IMAGE}
options:
  logging: CLOUD_LOGGING_ONLY
